### ISSUE TITLE
BANS method / Public DNS based wallet address

### ISSUE THREAD

**Issue by hellc** [Emurgo/yoroi-frontend#177]
# Abstract

The purpose of this method is to provide ability to link blockchain wallet or smart contract addresses with existing public domain names.

# Motivation

The main motivation was to provide an easiest way of DNS re-usage in case of blockchain addresses resolving compare with [Ethereum ENS](https://ens.domains/). To use ENS users should register a `.eth` domain name for themselves by participating in an auction process, mediated by the blockchain.

**BANS** will allow you to use any short and user friendly **domain names** that could be found by everyone thought the simple [procedure](https://github.com/hellc/bans#setup-guide) using **DNS over HTTPS** and **DNSSec** technics.

# Background

The main goal is to provide secured and anonymous features to link and retrieve your custom blockchain address based on public domain name you own.

**DNSSec** (Domain Name System Security Extensions) a set of extensions to DNS which provide to DNS clients (resolvers) origin authentication of DNS data, authenticated denial of existence, and data integrity, but not availability or confidentiality (if not Tor DNS servers).

If we keep calling DNS the phone book of the Internet, we could say that DNSSec is the protocol that ensures a number in the phone book (or blockchain address) actually belongs to the contact listed. It uses public-key cryptography to this end, and (in short):

- lets the DNS server signs records with a private key
- allows the DNS resolvers to verify the signatures with a public key

You could find an answers on security related questions from the following sources provided by `Mozilla`, `Cloudflare` and `IETF`:
1. [RFC 3658](https://tools.ietf.org/html/rfc3658)
2. [What is DNS over HTTPS](https://hacks.mozilla.org/2018/05/a-cartoon-intro-to-dns-over-https/)
3. [Mozilla Tests DNS over HTTPS](https://threatpost.com/mozilla-tests-dns-over-https-meets-some-privacy-pushback/130765/)
4. [How-does-DNSSEC-work](https://support.cloudflare.com/hc/en-us/articles/209641907-How-does-DNSSEC-work-) 

# Proposal

The main thing is that we should follow a unified specification scheme. You could also find an interactive example [here](https://github.com/hellc/bans) (code examples included).

We could integrate BANS address retrieval process during Yoroi **SEND** UX:

<img width="670" alt="screenshot 2018-12-17 at 10 54 43 pm" src="https://user-images.githubusercontent.com/750178/50112886-6fa1ec00-0251-11e9-82ce-450a73b71a2a.png">

It's possible by Cloudflare https API method (you could use for ex. _Google DNS Cloud_ API methods instead):
`curl -H 'acloudflare-dns.com/dns-query?name=bans.ada.0.kxp.one&type=TXT'`
**name=bans.ada.0.kxp.one** parameter is based on specification scheme.

response would be:

`{"Status": 0,"TC": false,"RD": true, "RA": true, "AD": false,"CD": false,"Question":[{"name": "bans.ada.0.kxp.one.", "type": 16}],"Answer":[{"name": "bans.ada.0.kxp.one.", "type": 16, "TTL": 300, "data": "\"Ae2tdPwUPEZ7f7RgToFi4EbUozdBNEYs34kRvSKPc33PUD93QUPT9JmxXwq\""}]`

We should validate DNSSec support to provide the best level of security.
If **AD** flag is **true**, it means that every record in the answer was verified with DNSSec.

> Note that **kxp.one** is not completely support DNSSec right now and its just an example. We need DS record support by registrar to achieve the best level of security. **AD** flag should be true.
> AD = Authenticated Data (for DNSSEC only; indicates that the data was authenticated)

> We could also check DS record. Example: `dig +short DS cloudflare.com` response: `2371 13 2 32996839A6D808AFE3EB4A795A0E6A7A39A76FC52FF228B22B76F6D6 3826F2B9` - **The DS** record stands for Delegation Signer, and it contains a hash of your public key as well as metadata about the key, such as what algorithm is uses.

Then we could validate **data** field as supported ADA wallet address.
If user is OK with retrieved (presented below the input field) address - allow him to send funds on it.

else if not **BANS** related info with the provided domain name - show a common error message:
<img width="678" alt="screenshot 2018-12-17 at 11 03 29 pm" src="https://user-images.githubusercontent.com/750178/50113375-c956e600-0252-11e9-858e-45a04afda720.png">

We could also provide a description about BANS method support in GENERAL SETTINGS screen (for example: in **Features** tab).

In the end we will get a very transparent BANS feature integration with a good profit of usage.

**Comment by HM999** [comment]
Seems reasonable to me. 

I think adding existing real world identities is as legitimate, or perhaps more legitimate than using SCs to create a new one like ENS Identities on Ethereum. 

I believe this is how Google Tools authenticate website ownership, so I'm thinking it is secure, of course the risk is someone spoofs the mapping somehow to point to another address. Is there an infosec person we can check with, just to list the ways someone might do that and how possible it actually is?

When designing the UI, be mindful that almost certainly Yoroi will want to add different identity -> address mappings in the future.

**Comment by hellc** [comment]
@hm999 It’s fun that it's still no dnssec signatures support on daedaluswallet.io ... https://dnssec-analyzer.verisignlabs.com/Daedaluswallet.io

**Comment by SebastienGllmt** [comment]
Thanks for submitting a feature request for triage. Could you submit these as PRs instead of issues going forward? Thanks!

Thoughts:
- Address in DNS means the address will always be the same (instead of one address / transaction) so there is a privacy loss to this feature. You could try and resolve this by having the BANS field change either periodically or every time a transaction occurs but caching will make this either not work as expected or be inefficient.
- We would need to pay for a security audit of this feature so there is a non-trivial cost to adding this
- I would expect low usage of this feature since most users would not have support for this on their machine and most system admins would not want to go through the work setting up their servers to do this safely. This is not necessarily a reason to turn down the feature but it's something to consider.

I would like to see:
1) How this compares to other standards such as [BIP-70](https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki)
1) Explanation for why to use this over [OpenAlias](https://openalias.org/)
1) Motivation for creating a new record type instead of using `TXT` (which is already supported by all servers and clients)

If there is a good reason to pick BANS over other standards, then I would rather see this as a CIP before we implement it ourselves in Yoroi

**Comment by vantuz-subhuman** [comment]
I would like to try and understand what exactly the problem we are trying to solve with this feature. Because "linking addresses to domain names" seems more like a solution to me, rather than the problem itself. And it might be that there's a simpler solution for the same problem, that does not invoke a whole lot of external infrastructure.

"Reverse engineering" problems that might be solved by this feature, I see something like this:
1. Users want to enter simple readable names, instead of long addresses when sending transactions
2. Website owners want to use their domain names to announce their receiving addresses 
3. Don't have to copy-paste long addresses from a webpage
4. ????

My thoughts on possible solutions for these problems:

#### Short readable names

Short readable names, imo, are basically only an issue when it's an address used often enough by the same user. If I send a one time donation to, e.g., wikipedia - it wouldn't hurt me to copy their address from the page where I just read about the fact that they ask for donations. On the other hand - hard-linking domain name with an address would limit website owners to 1 address, and would be impossible to have multiple addresses for different website sections, if they not separated by domains (for example: `website.com/shop`, `website.com/forum`, `website.com/education`).

I think the problem of having readable names is majorly solved by much more simple feature of "local address book", which is planned and wanted for a long time now, and a proposal for it should be added fairly soon.

A "local address book" would allow people to locally name any addresses, and then use these names instead of actual addresses when sending transactions. Additionally, address book, by being a two-way mapping, would allow us to use it to get names by addresses, thus displaying readable name for a sender when receiving payments (as would ENS, btw).

Latest feature proposals also show that we can potentially make this address-book shareable between user wallets and devices, thus solving the problem of it being strictly local.

#### Website owners announcing addresses to visitors

I understand this as the main point of the whole idea, right? If so, then at the very least it has the complication described above - one locked address per domain. So if I want to have multiple addresses for different causes - having multiple domains is the only solution. And if I want to have dynamic addresses - there's no solution at all.

I think the technology of web itself is very much getting optimised more and more toward website owners being able to securely deliver web-content to users, and there's already a whole industry of software (web browsers) working specifically with this whole ecosystem. I mean, if I'm a website owner, and I need to signal a crypto-address to my visitors - I can just create a special page on my website, or put the address at the bottom of every page, and then also duplicate the address on some other channels, so people can verify it if they want.

If user sends a transaction to an address they have verified from multiple channels - at least the whole blockchain system guarantees that the transaction will be sent to the right receiver. On the other hand if they send transaction to `website.com` - to my understanding there's no immediate mechanism to assure that it's actually going to the right address, apart from using a bunch of **external** mechanisms, foreign to the platform itself. Or, optionally, to require user to also verify the address with his own eyes, and then it's not very different from just copy-pasting the address itself from a webpage.

#### Don't have to copy-paste long addresses from a webpage

This problem, imo, is much simpler and much more flexible system of quick links (https://github.com/Emurgo/yoroi-frontend/issues/99) which is a very good idea and which we really want to implement at some point. Having quick-links would allow a website owner to not only create a link that opens Yoroi and pre-fills the receiver address, but also optionally specifies the transaction amount right away, or adds the address to the local address-book, etc.

## ENS

ENS is actually a very good alternative for this feature, at least for the fact that it fully operates **inside** the platform, without a need to actually register an external web-domain name and then also constantly function thru a foreign infrastructural set. Thus ENS is much more usable from a simple user POV that might easily register a name thru a simple sc-call thru a wallet, without going thru the whole DNS-record stuff. While BANS would require a user to register an **external** full-blown web-domain for every address and then constantly renew the subscription. So it more looks like a solution strictly for already website owners.

**Comment by HM999** [comment]
Probably what is really needed is a global decentralised identity system, that stores stuff about you / an entity, keyed on a unique identifier. Third parties interface with that system to get information as you allow it. Including things like crypto currency addresses for the identity.... but that system doesn't exist.

**Comment by HM999** [comment]
@vantuz-subhuman have you used ENS to obtain a name? - because from your description, I'd be willing to bet my house you havn't... of course the Cardano version could be made simpler I suppose.

**Comment by HM999** [comment]
We are talking here about mapping external identities (DN is one instance of such identities) to addresses/wallets (in this case a Cardano address).... it's a big topic, much bigger than a code change to Yoroi. Probably should ask CH and other people who have an overview of the whole space what they think.

**Comment by vantuz-subhuman** [comment]
> have you used ENS to obtain a name?

I am describing the basic idea of having a "name <> address" mapping in a smart-contract on CL, instead of using external infrastructure for that. Specifics of how users interact with this contract is not important and may be changed.

> We are talking here about mapping external identities (DN is one instance of such identities) to addresses/wallets (in this case a Cardano address)

I agree. I'm just not sure it's a needed feature that would solve some problem and be useful to Yoroi users right now. 

> it's a big topic, much bigger than a code change to Yoroi. Probably should ask CH and other people who have an overview of the whole space what they think.

Fair enough, it might be moved to the forum or something, and subjected to a discussion. In the scope of specific proposal of adding a new feature to the Yoroi codebase - I feel like it's not yet completely worked thru on why exactly would users need it and why exactly this technological solution is the best one.

**Comment by prographo** [comment]
A very important use-case.

The Problem: People don't like using the long strings of characters to send money. You have to cut and paste, if you type it, you will make a mistake and lose your funds, cut and paste is insecure (cut'n'paste hack). It's unverified, when I paste in this horrible string, there is no kind of hint I got it right. Bank transfers also use a string of digits, but only 8-12 digits, which is manageable (but still scary; my mom actually calls my dad over to "check the number").  

NB: The use-case where the mapping to an address is 1:1 is the most common use-case, it is synonymous to me giving you my bank account details so you can pay me for something. Personally I think the functionality to have multiple addresses should be hidden from novice users, it's confusing and scary.

Without any thoughts to implementation, this is how it should work for a user: Grandma, opens her wallet. She is sending me funds for the first time. She types in the short-name I gave her. The address is automatically filled in, my full name and a picture of myself is displayed.

It needs to be that simple. Grandma don't have time for base58 strings.

**Comment by vantuz-subhuman** [comment]
> Without any thoughts to implementation, this is how it should work for a user: Grandma, opens her wallet. She is sending me funds for the first time. She types in the short-name I gave her. The address is automatically filled in, my full name and a picture of myself is displayed.

Be sure that we are thinking about this case very much and very carefully and gradually working toward Yoroi supporting something like this 🙂 But this particular discussion is all about that this proposed feature is not a good way to solve this particular problem, because it would, for example, require you to rent yourself an actual domain/website address (like `prographo.com`), and then also perform manual DNS configuration (see [spec](https://github.com/hellc/bans#setup-guide)), and then also keep paying rent for that address. And after all this your grandma wouldn't be able to see your name when you send coins to her, because it would be impossible to search for your name by your address.

For this particular problem you are talking about we would want users to have an easier and more comfortable solution )

**Comment by HM999** [comment]
@vantuz-subhuman If it can be done within Cardano such that ANY identity can be mapped, then that would include this DN use case. There are many existing real-world identities that ppl will likely want to map, so something that captures all these use cases in one solution would be better imho. 

re: copy & paste attacks. These have only been done on BTC until now afaik. They will expand and they will catch a lot of ppl. because everyone uses copy & paste for addresses. Ideally any address mapping solution would also work in reverse. So if I paste an address into the wallet, and that address has meta data stored against it, the meta data gets displayed. This would prevent copy & paste attacks.

I know what you mean about addresses changing, probably what we are really want is mapping identities to/from an "account"; the level under a wallet but above addresses, which Cardano doesn't presently use; m/44/ADA/<Account>/ ... ?
