### ISSUE TITLE
Wallet Link to Cardano Explorer

### ISSUE THREAD

**Issue by adamparish** [Emurgo/yoroi-frontend#209]
As a Yoroi Wallet user, I would like the ability to see my wallet balance on the Cardano Explorer. This will allow me as a user to easily confirm my balance on the chain and increase my level of trust with Yoroi and the Cardano Platform.

Here's an example of this feature on MetaMask.

![screenshot 2019-01-01 at 1 32 53 pm](https://user-images.githubusercontent.com/272088/50575329-637a6a80-0dcb-11e9-8efe-7b18d71c5480.png)
(The "View on Etherscan" text is a link that will take you to the wallet address for this MetaMask account on etherscan.io)

**Comment by adamparish** [comment]
I don't see how to add the label "Help Wanted"

**Comment by vantuz-subhuman** [comment]
> I would like the ability to see my wallet balance on the Cardano Explorer

It's an understandable wish and we want and plan to add something similar. The problem right now is that Cardano Explorers can't show you a **wallet** balance. Because of the UTxO system - each wallet often controls multiple addresses and any explorer only can show you balance for a single address. So a single link "View in explorer" is technically impossible, unless it will potentially open tens or hundreds of tabs for all the different addresses. And just pointing from addresses to an explorer might be misleading, because Yoroi at the moment does not show users their internal (change) addresses, so they potentially might be able to see only a part of their overall balance on an explorer, which might be (and has been in the past) confusing.

We are thinking hard on this problem and trying to come up with the best possible solution that would allow people to double-check the information.

**Comment by adamparish** [comment]
@vantuz-subhuman thanks for the response. You definitely understand my ask. I'm glad. Based on your response it sounds like UTxO by design creates a bit more complexity for the end-user if they turn to the Cardano Explorer for additional insight. 

I wrote a bit about my Yoroi Wallet First Experiences on the Cardano Forum. You will see that I was confused by the lack of ability to see my wallet balance in one place on the chain. 

https://forum.cardano.org/t/yoroi-wallet-first-use-impression/19066/31?u=adam_parish

I'm glad the Yoroi team is thinking about this. Feel free to close out this Issue. I'm going to research UTxO a bit so that I can better understand the benefit of this approach.

**Comment by SebastienGllmt** [comment]
Closing this since we've already started working on this and will be included in the next release
