### ISSUE TITLE
Cannot send my ADA from Yoroi to Binance

### ISSUE THREAD

**Issue by Russty0077** [Emurgo/yoroi-frontend#2161]
I have sent some ADA before to Binance my nano is up to date but today when I have tried to send to the same address I just get a pop up window saying emurgo.github.io wants to connect to a HID device and nothing happens , its very frustrating

**Comment by JohnGiz** [comment]
I have the same problem.  Did you manage to solve it?

**Comment by JohnGiz** [comment]
Ok, got it!  You have to press on the NanoS or NanoX in the pop-up window.  Then press Confirm.  Don't understand why they changed this from the way it was before?

**Comment by zuzunker** [comment]
Seems like a change on the Ledger side as I think we have not made any changes to any of the bridge UX for a while now. Will look if there's anything we can do to upgrade or improve 👍

**Comment by dancaro1** [comment]
JohnGiz 
I am still struggling with this issue it says (nano s - paired) but the loading icon continues to spin on the ledger continues to say waiting for command

**Comment by JohnGiz** [comment]
Yeah, I went through it again yesterday.  Don't know what the hell the problem is.  Very frustrating.  I must've tried 20 times, and then, somehow, I got it.  Then I did it for voting again, and I got it.  So, I tried to figure out what the trick is and tried to send a small am't to another wallet, I got stuck, and can't do it again.  I dread the day I when I have to cash some out and will not be able to.  I opened another account on Yoroi that does not go through the Nano, so I can move things quickly if i have to.  So, in summary, my Nano S, worked after an hour of trying diff. things, and my Nano X, forget it .....   I'm pissed.  Don't know what changed bec. a few months ago things worked well.

**Comment by JohnGiz** [comment]
Ok, I finally got it to work, **for me**.  Here are the instructions:

SENDING ADA THROUGH LEGER NANO S:

1.  Write out the order, ie.  sending address, am't, etc.  Press Next.

2.  Send with Ledger.

3.  Nano S.   Continue.

4.  Pop out window.

5.  Connect Ledger.  Do the Pin.  Go to Cardano app.

6.  Pop out window will say Nano S is paired.

7.  Press both buttons on Ledger Nano S.  You get  "Waiting for Commands".

8.  Press Cancel in pop out window.

9.  Press "Send using Ledger".  Press "Continue" again (Green button).

Now, you get those 6 pics. telling you how to confirm the transaction. 

10.  Press right button on the Ledger, ie. Start new trans.

11.  Continue with Ledger, confirming sending address, etc.

Have a f***ing beer because this is insane.  Skip one step and you're back at 0. 

My Nano X is synced with Nano S, and yet I can't get it to work.

**Comment by sergeyrar** [comment]
> Ok, I finally got it to work, **for me**. Here are the instructions:
> 
> SENDING ADA THROUGH LEGER NANO S:
> 
> 1. Write out the order, ie.  sending address, am't, etc.  Press Next.
> 2. Send with Ledger.
> 3. Nano S.   Continue.
> 4. Pop out window.
> 5. Connect Ledger.  Do the Pin.  Go to Cardano app.
> 6. Pop out window will say Nano S is paired.
> 7. Press both buttons on Ledger Nano S.  You get  "Waiting for Commands".
> 8. Press Cancel in pop out window.
> 9. Press "Send using Ledger".  Press "Continue" again (Green button).
> 
> Now, you get those 6 pics. telling you how to confirm the transaction.
> 
> 1. Press right button on the Ledger, ie. Start new trans.
> 2. Continue with Ledger, confirming sending address, etc.
> 
> Have a f***ing beer because this is insane. Skip one step and you're back at 0.
> 
> My Nano X is synced with Nano S, and yet I can't get it to work.

Didn't work for me.
I did steps 1-9.
After step 9, window simply got closed.

**Comment by JohnGiz** [comment]
Sorry to hear, man!  It did work for some people.
    On Wednesday, October 6, 2021, 12:27:31 p.m. EDT, sergey ***@***.***> wrote:  
 
 



Ok, I finally got it to work, for me. Here are the instructions:

SENDING ADA THROUGH LEGER NANO S:
   
   - Write out the order, ie. sending address, am't, etc. Press Next.
   - Send with Ledger.
   - Nano S. Continue.
   - Pop out window.
   - Connect Ledger. Do the Pin. Go to Cardano app.
   - Pop out window will say Nano S is paired.
   - Press both buttons on Ledger Nano S. You get "Waiting for Commands".
   - Press Cancel in pop out window.
   - Press "Send using Ledger". Press "Continue" again (Green button).

Now, you get those 6 pics. telling you how to confirm the transaction.
   
   - Press right button on the Ledger, ie. Start new trans.
   - Continue with Ledger, confirming sending address, etc.

Have a f***ing beer because this is insane. Skip one step and you're back at 0.

My Nano X is synced with Nano S, and yet I can't get it to work.


Didn't work for me.
I did steps 1-9.
After step 9, window simply got closed.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sergeyrar** [comment]
Issue resolved.

What I had to do was to update Cardano software on my Ledger.
I did this via Ledger Live -> Manager

**Comment by JohnGiz** [comment]
Oh, great!  I just did a transfer also.  I used the same steps that I outlined above and it worked. For some reason I can't do it with my Nano X.  Anyway, Sergey, glad you got it to work!!!
    On Thursday, October 7, 2021, 10:36:23 a.m. EDT, sergey ***@***.***> wrote:  
 
 


Issue resolved.

What I had to do was to update Cardano software on my Ledger.
I did this via Ledger Live -> Manager

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
