### ISSUE TITLE
Getting a blank popup window when trying to sign a transaction with ergo-dapp-connector

### ISSUE THREAD

**Issue by oskin1** [Emurgo/yoroi-frontend#2162]

**Comment by oskin1** [comment]
@rooooooooob any ideas why this could happen?

**Comment by oskin1** [comment]
looks like it's loading forever
https://ibb.co/Qb63Vc7

**Comment by oskin1** [comment]
It seems the problem is that the following request to Yoroi backend fails:

```
curl 'https://ergo-backend.yoroiwallet.com/api/assets/info' \
  -H 'authority: ergo-backend.yoroiwallet.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'yoroi-version: 4.4.1' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36' \
  -H 'yoroi-locale: en-US' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'origin: chrome-extension://poonlenmfdfbjfeeballhiibknlknepo' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,la;q=0.6' \
  --data-raw '{"assetIds":["2160263df60adb3dfe0431a871a3fc3c01c33c62220e33b2d02facd442a12c0b"]}' \
  --compressed
```

![2021-06-07 12 00 55](https://user-images.githubusercontent.com/29578480/120989275-077c5300-c788-11eb-89c6-f04f2227b5a5.jpg)

**Comment by oskin1** [comment]
The reason is that Yoroi tries to fetch asset info for a new token, which doesn't exist yet. It seems Yoroi is totally incapable of handling transactions that issue new assets.

**Comment by rooooooooob** [comment]
Okay I've managed to reproduce this locally and yes you are right that we don't handle signing new txs from the UI side. It looks like we try to look up the token info on the backend and it fails since the tokenId doesn't exist yet, since we are creating it in this transaction. We should be able to fix this by changing the UI code to use the current tx's minted assets instead of just querying the backend. I didn't write the UI portion of the connector so I'll inform the dev who did. Thanks for the report. We had only tested the connector on existing assets, not newly minted ones. As mentioned in #2157 we'll need to be updating how the UI gets asset info anyway since there are other cases where it can fail as well.

**Comment by zuzunker** [comment]
> The reason is that Yoroi tries to fetch asset info for a new token, which doesn't exist yet. Seems It seems Yoroi is totally incapable of handling transactions that issue new assets.

Good point. We'll try to fix this one in high priority
