### ISSUE TITLE
Multiple wallet account support in one Yoroi installation

### ISSUE THREAD

**Issue by sarveshwar-singh** [Emurgo/yoroi-frontend#238]
# Abstract

User could use multiple wallet account in one Yoroi installation 

# Motivation

It will give use more flexibility to use multiple account without installing multiple Yoroi.

# Background

# Proposal

User could use multiple wallet account in one Yoroi installation

**Comment by vantuz-subhuman** [comment]
We need to make a very clear distinction between **multiple wallets** in the same Yoroi, or **multiple accounts** in the same single wallet. Because "account" has already a very specific meaning in HD wallets we are using ([bip32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#the-default-wallet-layout))

**Comment by stevebayerin** [comment]
I would like to see multiple wallet management in one browser app for use cases where one user may be securing funds for multiple users who are not technically savvy.

Each wallet should be recoverable by a 15 word pass phrase given to each user in the event that the manager of the accounts is no longer available to recover the wallets. 15 word passphrases are easier to store on paper than secret keys and more recognizable as a recovery option.

**Comment by SebastienGllmt** [comment]
Closing since the storage spec described how we will implement this
