### ISSUE TITLE
[Feature Request] Reestablish or make optional: Block of reward display.

### ISSUE THREAD

**Issue by dideldei** [Emurgo/yoroi-frontend#2419]
I consider the reward display very helpful and motivating. Please reestablish it or let it be enabled or disabled.

**Comment by maxcleme** [comment]
IMO looks like it will be temporary since it has been toggled off instead of pure code deletion

https://github.com/Emurgo/yoroi-frontend/commit/d84416aa8db4291f76b090079e98030f2cd62b3b

**Comment by zuzunker** [comment]
Hi! Yes, sorry for this, we had to temporarily disable the historical data display as we are still experiencing 3rd-party complications for correct chain data reading since the Alonzo update. The immediate rewards information, available for withdrawal have been corrected, but we had to sacrifice the historical data for now. It was a quick decision without proper UI replacement, we are planning to have an intermediate release now which will have an explanation that historical data will be back as soon as technically possible. At the moment it seems like might have it back next week.
