### ISSUE TITLE
Edge is out of date

### ISSUE THREAD

**Issue by mpdelbuono** [Emurgo/yoroi-frontend#2421]
I'm not sure why as Edge can load Chrome extensions, but the Edge store version is currently 4.7.200 (two versions behind the current release for both Firefox and Chrome, which is on 4.7.400).

Please release to Edge store in addition to Chrome store, as users who have installed from Edge store will not get updated unless it is released on Edge store.

**Comment by zuzunker** [comment]
Hi, @mpdelbuono! Edge release time takes few days from the moment the new version is submitted, while for Chrome and FF it takes 5-15 minutes. The version 4.7.400 have been submitted to Edge at the same moment with other stores, but it is still in review and Microsoft even writes **"Expect to hear back from us in 7 business days"**, so not even **within** 7 business days. The version 4.7.300 actually never have been released to Edge just because the 4.7.400 became available before the review have been finished.

So this is the reality of Microsoft that we have to deal with. Since MS disabled chrome-store apps in Edge in favor of their own store - Edge version will always be ~1 week later for every release.

![image](https://user-images.githubusercontent.com/5585355/135286021-c1dffb64-bc1c-4be7-b8b8-34ecd0dcdd67.png)
