### ISSUE TITLE
Not all generated addresses are shown

### ISSUE THREAD

**Issue by travek** [Emurgo/yoroi-frontend#260]
Hi!
I'm Yoroi user. I have an issue with correct reflection in the interface of all generated accounts.
Yoroi wallet is showing my balance = X.
I have only 2 accounts in the Generated accounts section.
Sum of these two accounts balances (=X1) is less than the wallet balance, X1<X !
It means that there were other accounts generated that have balances but these accounts are not shown in the generated accounts section of the interface.

Please, fix this issue. 
It's really uncomfortable to have a discrepance between wallet balance and reflected accounts balances

**Comment by vantuz-subhuman** [comment]
Hello, @travek, and thank you for the report! 🙌 

1. I had to change the title, because what you are talking about is "generated **addresses**", not accounts. Accounts have a particular meaning in the HD wallet standard that we are using ([BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)).

2. Yes, unfortunately, it is a known issue, currently our UI does not display the "internal" addresses that are used to receive "change" from when you are sending a transaction. You can see those internal addresses in transaction details. For example, when I send a transaction from Yoroi to Daedalus (to long `Ddz` address) - transaction shows "To addresses" and there are two addresses: one long and one short. The short one is my own address where I receive the change, but this address is not displayed on the "Generated addresses":

![image](https://user-images.githubusercontent.com/5585355/51800176-aac61080-223c-11e9-9691-e2554ce05259.png)

This is rather a design shortcoming, and not a technical bug, because at the beginning of the app it was decided to go with a particular standard-related design decision to keep change addresses as truly "internal" and not have then known even to user, in order to keep user from accidentally use those to receive funds (e.g. https://bitcoin.stackexchange.com/a/75037).

There are internal discussion happening now in our team, where I tried to bring up some possible solutions on how we can make those addresses transparent and visible, but not make them equal to the external receive addresses. It is still a major work in progress, but please be assured that we pretty much want to move away from how it works right now 🤞

**Comment by travek** [comment]
@vantuz-subhuman, 
yes the problem appeared when sending between short- and long- addresses happened.

Thanks for feedback!
Waiting for the fix in the future.

**Comment by SebastienGllmt** [comment]
Closing this to track this feature in #338
