### ISSUE TITLE
 Yoroi extension on Chrome is stuck with white screen on launch

### ISSUE THREAD

**Issue by sharkfin22** [Emurgo/yoroi-frontend#3700]
Version 5.4.0

When I open yoroi on firefox the wallets don't load up properly. Its stuck on a white screen with just the yoroi logo. 

The following is the firefox console output. 

```
[yoroi] closing other instances [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi][preLoadingScreenEnd] [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] loading ended [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
extension / loading store loaded [yoroi.bundle.js:1:1298430](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/yoroi.bundle.js)
[yoroi] stores created [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] root located [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] messages merged [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] themes changed [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi/prod] checking if should inject dapp-connector api [inject.js:62:17](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/inject.js)
[yoroi/prod] injecting over 'nothing' [inject.js:65:21](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/inject.js)
[yoroi/prod] dapp-connector is successfully injected into emurgo.github.io [inject.js:38:17](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/inject.js)
Removing unpermitted intrinsics [lockdown-install.js:1:52832](moz-extension://gggggg-gggg-gggg-gggg-ggggggggg/scripts/lockdown-install.js)
Uncaught (in promise) Error: [BigNumber Error] Not a number: [object Object]
    w moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/4291.bundle.js:2
    q moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/4291.bundle.js:2
    from moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/8381.bundle.js:1
    from moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/8381.bundle.js:1
    we moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/yoroi.bundle.js:1
    Ce moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/yoroi.bundle.js:1
```

![image](https://github.com/user-attachments/assets/f9b59b7a-7234-40ba-913e-4da1267a6e30)

**Comment by Julietnacy** [comment]
@sharkfin22 Have you tried clearing your browser cache or disabling any extensions that might be interfering?

**Comment by LeoNore-ort** [comment]
@sharkfin22 Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [IOHK / Yoroi support](https://cardano-zendesk.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by b4zyl** [comment]
Same issue here, Yoroi stucks on Logo screen in Firefox. Checked on two devices.
I did also deleted Firefox Yoroi extension and installed back again. Cannot even restore wallet now. 
Wallet just worked few days back.

**Comment by v-niskala** [comment]
Got the same issue. I reinstalled the firefox extension and I can't connect to my Ledger. I got it to work in Chrome though

**Comment by sharkfin22** [comment]
@vsubhuman any updates on this?

**Comment by sharkfin22** [comment]
still unusable.

**Comment by arrowd** [comment]
The same problem still persists on Firefox (or the extension didn't get an update)

**Comment by zuzunker** [comment]
> The same problem still persists on Firefox (or the extension didn't get an update)

Hi, @arrowd! The Firefox fix is unfortunately blocked by the Firefox store procedures. A chrome release takes minutes or hours, a Firefox release in a regular situation takes 5 days.

But with this particular situation we have tried to push a rollback release to Firefox one day after discovering the issue, but instead of 5 days it got stuck in Firefox review for 10 days and then got rejected with a request to make some UI changes for legal reasons. Which we are implementing at the moment ASAP.

So just to reiterate, the rollback to an older build which WAS already public in Firefox prior to the unsuccessful 5.4 update, got rejected this time with some compliance requirements, even though that same exact build was previously already reviewed, approved, and published.

After requesting compliance clarifications, it took another 6 days to get a response from Firefox, so we could know what exactly is needed to pass the review process for sure.

In the meantime we have upgraded our release pipelines to better assure Firefox compatibility for each version. But when an unfortunate situation happens, this is the price we are paying for Firefox to not have AI reviews and have stricter review processes. (Even though they do approve and publish builds that later might turn out to not comply with their requirements.)

**Comment by sharkfin22** [comment]
@vsubhuman thank you for the update! Really appreciate it.

**Comment by zuzunker** [comment]
@arrowd , after finally receiving proper clarifications from Firefox on the Oct 6th we have implemented all the required changes within yesterday Oct 7th and now the new version which will hopefully pass all their requirements is being submitted on Oct 8th. 

Look out for version `5.4.279`. As I already mentioned getting any release through their store still unfortunately takes around five days in a good case. I will send an update in case we get any news.

Note that by the Firefox requirements **ALL** existing extension users (on firefox only) will get an automatic tab opened with the Yoroi analytics consent whenever their extension gets updated to this new release. This is due to the FF worry that not all users might have seen it before, because we did not open it up automatically right after the app installation (even tho it was mandatory displayed to all users when they opened the app manually).

**Comment by zuzunker** [comment]
After waiting for usual 5 days we have received a rejection from Firefox with additional requirements that they have not mentioned in the first place. Within a day a new version has been implemented and submitted for review again. So far 2 days have passed and we are waiting for the next update on that probably within next 3 days.

**Comment by zuzunker** [comment]
After 6 days in review the firefox store has finally accepted the updated compliance build. The version `5.4.280` is now available in the store and should be working for everyone.

**Comment by arrowd** [comment]
I confirm, it finally works. Thank you!

**Comment by zuzunker** [comment]
> I confirm, it finally works. Thank you!

Thank you!

**Comment by sharkfin22** [comment]
Its working. Thank you very much for making this work. More kudos for putting up with Firefox's ridiculous policies and procedures. Really appreciate it!!

**Comment by zuzunker** [comment]
> Really appreciate it!!

Thank you! 🙌
