### ISSUE TITLE
How to get Daedalus master key from Daedalus memo?

### ISSUE THREAD

**Issue by mmo2112** [Emurgo/yoroi-frontend#878]
Hi, I have Daedalus memo and I want to get master key from these memo to contact with Yoroi/wasp (for few reasons). Is there any method to get master key? The difference is between BIP39 vs 44 makes wrong while converting:
```
const cardano = require('cardano-wallet');
const dMemo = ...;
const dEntropy = cardano.Entropy.from_english_mnemonics(words);
const dWallet = cardano.DaedalusWallet.recover(dEntropy);
const privateKey = cardano.PrivateKey.new(dEntropy);
const pk = privateKey.to_hex();
console.log("pk", pk);
```
Thanks so much for help.

**Comment by SebastienGllmt** [comment]
I don't think the WASM bindings allow you to easily extract the Daedalus master key but it's not too hard to do if you don't mind adding the feature to the WASM codebase. 
You can see some of my PRs [here](https://github.com/input-output-hk/js-cardano-wasm/pulls?q=is%3Apr+is%3Aclosed) on how to add code to the WASM codebase. You're welcome to create a PR yourself to add the feature (we don't need it for Yoroi but others may find it useful).

I'm going to close the issue here since the feature you're requesting is a feature for `js-cardano-wasm` not Yoroi-Frontend. You're welcome to recreate the issue there 👍
